/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  DirectionsParams,
  DirectionsResponse
} from './model';






/**
 * The Directions API is a web service that uses an HTTP request to return JSON or XML-formatted directions between locations. You can receive directions for several modes of transportation, such as transit, driving, walking, or cycling.
 */
export const directions = (
    params: DirectionsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DirectionsResponse>> => {
    
    
    return axios.get(
      `/maps/api/directions/json`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getDirectionsQueryKey = (params?: DirectionsParams,) => {
    return [
    `/maps/api/directions/json`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getDirectionsQueryOptions = <TData = Awaited<ReturnType<typeof directions>>, TError = AxiosError<unknown>>(params: DirectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof directions>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDirectionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof directions>>> = ({ signal }) => directions(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof directions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DirectionsQueryResult = NonNullable<Awaited<ReturnType<typeof directions>>>
export type DirectionsQueryError = AxiosError<unknown>


export function useDirections<TData = Awaited<ReturnType<typeof directions>>, TError = AxiosError<unknown>>(
 params: DirectionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof directions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof directions>>,
          TError,
          Awaited<ReturnType<typeof directions>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirections<TData = Awaited<ReturnType<typeof directions>>, TError = AxiosError<unknown>>(
 params: DirectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof directions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof directions>>,
          TError,
          Awaited<ReturnType<typeof directions>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDirections<TData = Awaited<ReturnType<typeof directions>>, TError = AxiosError<unknown>>(
 params: DirectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof directions>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDirections<TData = Awaited<ReturnType<typeof directions>>, TError = AxiosError<unknown>>(
 params: DirectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof directions>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDirectionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



