/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  DistanceMatrixParams,
  DistanceMatrixResponse
} from './model';






/**
 * The Distance Matrix API is a service that provides travel distance and time for a matrix of origins and destinations. The API returns information based on the recommended route between start and end points, as calculated by the Google Maps API, and consists of rows containing duration and distance values for each pair.
 */
export const distanceMatrix = (
    params: DistanceMatrixParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DistanceMatrixResponse>> => {
    
    
    return axios.get(
      `/maps/api/distancematrix/json`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getDistanceMatrixQueryKey = (params?: DistanceMatrixParams,) => {
    return [
    `/maps/api/distancematrix/json`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getDistanceMatrixQueryOptions = <TData = Awaited<ReturnType<typeof distanceMatrix>>, TError = AxiosError<unknown>>(params: DistanceMatrixParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof distanceMatrix>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDistanceMatrixQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof distanceMatrix>>> = ({ signal }) => distanceMatrix(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof distanceMatrix>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DistanceMatrixQueryResult = NonNullable<Awaited<ReturnType<typeof distanceMatrix>>>
export type DistanceMatrixQueryError = AxiosError<unknown>


export function useDistanceMatrix<TData = Awaited<ReturnType<typeof distanceMatrix>>, TError = AxiosError<unknown>>(
 params: DistanceMatrixParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof distanceMatrix>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof distanceMatrix>>,
          TError,
          Awaited<ReturnType<typeof distanceMatrix>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDistanceMatrix<TData = Awaited<ReturnType<typeof distanceMatrix>>, TError = AxiosError<unknown>>(
 params: DistanceMatrixParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof distanceMatrix>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof distanceMatrix>>,
          TError,
          Awaited<ReturnType<typeof distanceMatrix>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDistanceMatrix<TData = Awaited<ReturnType<typeof distanceMatrix>>, TError = AxiosError<unknown>>(
 params: DistanceMatrixParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof distanceMatrix>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDistanceMatrix<TData = Awaited<ReturnType<typeof distanceMatrix>>, TError = AxiosError<unknown>>(
 params: DistanceMatrixParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof distanceMatrix>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDistanceMatrixQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



