/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Elevation200,
  ElevationParams
} from './model';






/**
 * The Elevation API provides a simple interface to query locations on the earth for elevation data. Additionally, you may request sampled elevation data along paths, allowing you to calculate elevation changes along routes. With the Elevation API, you can develop hiking and biking applications, positioning applications, or low resolution surveying applications.

Elevation data is available for all locations on the surface of the earth, including depth locations on the ocean floor (which return negative values). In those cases where Google does not possess exact elevation measurements at the precise location you request, the service interpolates and returns an averaged value using the four nearest locations. Elevation values are expressed relative to local mean sea level (LMSL).

Requests to the Elevation API utilize different parameters based on whether the request is for discrete locations or for an ordered path. For discrete locations, requests for elevation return data on the specific locations passed in the request; for paths, elevation requests are instead sampled along the given path.

 */
export const elevation = (
    params?: ElevationParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Elevation200>> => {
    
    
    return axios.get(
      `/maps/api/elevation/json`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getElevationQueryKey = (params?: ElevationParams,) => {
    return [
    `/maps/api/elevation/json`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getElevationQueryOptions = <TData = Awaited<ReturnType<typeof elevation>>, TError = AxiosError<unknown>>(params?: ElevationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof elevation>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getElevationQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof elevation>>> = ({ signal }) => elevation(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof elevation>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ElevationQueryResult = NonNullable<Awaited<ReturnType<typeof elevation>>>
export type ElevationQueryError = AxiosError<unknown>


export function useElevation<TData = Awaited<ReturnType<typeof elevation>>, TError = AxiosError<unknown>>(
 params: undefined |  ElevationParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof elevation>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof elevation>>,
          TError,
          Awaited<ReturnType<typeof elevation>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useElevation<TData = Awaited<ReturnType<typeof elevation>>, TError = AxiosError<unknown>>(
 params?: ElevationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof elevation>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof elevation>>,
          TError,
          Awaited<ReturnType<typeof elevation>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useElevation<TData = Awaited<ReturnType<typeof elevation>>, TError = AxiosError<unknown>>(
 params?: ElevationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof elevation>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useElevation<TData = Awaited<ReturnType<typeof elevation>>, TError = AxiosError<unknown>>(
 params?: ElevationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof elevation>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getElevationQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



