/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GeocodeParams,
  GeocodingResponse
} from './model';






/**
 * The Geocoding API is a service that provides geocoding and reverse geocoding of addresses.

**Geocoding** is the process of converting addresses (like a street address) into geographic coordinates (like latitude and longitude), which you can use to place markers on a map, or position the map.

**Reverse geocoding** is the process of converting geographic coordinates into a human-readable address.

You can also use the Geocoding API to find the address for a given place ID.

To see countries currently supported by the Google Maps Platform Geocoding API, please consult the [Google Maps coverage data](https://developers.google.com/maps/coverage). The accuracy of geocoded locations may vary per country, so you should consider using the returned `location_type` field to determine if a good enough match has been found for the purposes of your application. Please note that the availability of geocoding data depends on our contracts with data providers, so it is subject to change.
 */
export const geocode = (
    params?: GeocodeParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GeocodingResponse>> => {
    
    
    return axios.get(
      `/maps/api/geocode/json`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGeocodeQueryKey = (params?: GeocodeParams,) => {
    return [
    `/maps/api/geocode/json`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGeocodeQueryOptions = <TData = Awaited<ReturnType<typeof geocode>>, TError = AxiosError<unknown>>(params?: GeocodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geocode>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGeocodeQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof geocode>>> = ({ signal }) => geocode(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof geocode>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GeocodeQueryResult = NonNullable<Awaited<ReturnType<typeof geocode>>>
export type GeocodeQueryError = AxiosError<unknown>


export function useGeocode<TData = Awaited<ReturnType<typeof geocode>>, TError = AxiosError<unknown>>(
 params: undefined |  GeocodeParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof geocode>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof geocode>>,
          TError,
          Awaited<ReturnType<typeof geocode>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGeocode<TData = Awaited<ReturnType<typeof geocode>>, TError = AxiosError<unknown>>(
 params?: GeocodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geocode>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof geocode>>,
          TError,
          Awaited<ReturnType<typeof geocode>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGeocode<TData = Awaited<ReturnType<typeof geocode>>, TError = AxiosError<unknown>>(
 params?: GeocodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geocode>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGeocode<TData = Awaited<ReturnType<typeof geocode>>, TError = AxiosError<unknown>>(
 params?: GeocodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geocode>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGeocodeQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



