/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ErrorResponse,
  GeolocationRequest,
  GeolocationResponse
} from './model';






/**
 * Geolocation API returns a location and accuracy radius based on information about cell towers and WiFi nodes that the mobile client can detect. This document describes the protocol used to send this data to the server and to return a response to the client.

Communication is done over HTTPS using POST. Both request and response are formatted as JSON, and the content type of both is `application/json`.

You must specify a key in your request, included as the value of a`key` parameter. A `key` is your application's  API key. This key identifies your application for purposes of quota management. Learn how to [get a key](https://developers.google.com/maps/documentation/geolocation/get-api-key).
 */
export const geolocate = (
    geolocationRequest?: GeolocationRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GeolocationResponse>> => {
    
    
    return axios.post(
      `/geolocation/v1/geolocate`,
      geolocationRequest,options
    );
  }



export const getGeolocateMutationOptions = <TError = AxiosError<ErrorResponse | ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof geolocate>>, TError,{data: GeolocationRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof geolocate>>, TError,{data: GeolocationRequest}, TContext> => {

const mutationKey = ['geolocate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof geolocate>>, {data: GeolocationRequest}> = (props) => {
          const {data} = props ?? {};

          return  geolocate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GeolocateMutationResult = NonNullable<Awaited<ReturnType<typeof geolocate>>>
    export type GeolocateMutationBody = GeolocationRequest
    export type GeolocateMutationError = AxiosError<ErrorResponse | ErrorResponse>

    export const useGeolocate = <TError = AxiosError<ErrorResponse | ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof geolocate>>, TError,{data: GeolocationRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof geolocate>>,
        TError,
        {data: GeolocationRequest},
        TContext
      > => {

      const mutationOptions = getGeolocateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    