/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  NearestRoadsErrorResponse,
  NearestRoadsParams,
  NearestRoadsResponse,
  SnapToRoadsParams,
  SnapToRoadsResponse
} from './model';






/**
 * This service returns the best-fit road geometry for a given set of GPS coordinates. This service takes up to 100 GPS points collected along a route, and returns a similar set of data with the points snapped to the most likely roads the vehicle was traveling along. Optionally, you can request that the points be interpolated, resulting in a path that smoothly follows the geometry of the road.
 */
export const snapToRoads = (
    params: SnapToRoadsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SnapToRoadsResponse>> => {
    
    
    return axios.get(
      `/v1/snaptoroads`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getSnapToRoadsQueryKey = (params?: SnapToRoadsParams,) => {
    return [
    `/v1/snaptoroads`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSnapToRoadsQueryOptions = <TData = Awaited<ReturnType<typeof snapToRoads>>, TError = AxiosError<unknown>>(params: SnapToRoadsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof snapToRoads>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSnapToRoadsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof snapToRoads>>> = ({ signal }) => snapToRoads(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof snapToRoads>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SnapToRoadsQueryResult = NonNullable<Awaited<ReturnType<typeof snapToRoads>>>
export type SnapToRoadsQueryError = AxiosError<unknown>


export function useSnapToRoads<TData = Awaited<ReturnType<typeof snapToRoads>>, TError = AxiosError<unknown>>(
 params: SnapToRoadsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof snapToRoads>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof snapToRoads>>,
          TError,
          Awaited<ReturnType<typeof snapToRoads>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSnapToRoads<TData = Awaited<ReturnType<typeof snapToRoads>>, TError = AxiosError<unknown>>(
 params: SnapToRoadsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof snapToRoads>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof snapToRoads>>,
          TError,
          Awaited<ReturnType<typeof snapToRoads>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSnapToRoads<TData = Awaited<ReturnType<typeof snapToRoads>>, TError = AxiosError<unknown>>(
 params: SnapToRoadsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof snapToRoads>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSnapToRoads<TData = Awaited<ReturnType<typeof snapToRoads>>, TError = AxiosError<unknown>>(
 params: SnapToRoadsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof snapToRoads>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSnapToRoadsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * This service returns individual road segments for a given set of GPS coordinates. This services takes up to 100 GPS points and returns the closest road segments for each point. The points passed do not need to be part of a continuous path.
 */
export const nearestRoads = (
    params: NearestRoadsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<NearestRoadsResponse>> => {
    
    
    return axios.get(
      `/v1/nearestRoads`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getNearestRoadsQueryKey = (params?: NearestRoadsParams,) => {
    return [
    `/v1/nearestRoads`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getNearestRoadsQueryOptions = <TData = Awaited<ReturnType<typeof nearestRoads>>, TError = AxiosError<NearestRoadsErrorResponse>>(params: NearestRoadsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof nearestRoads>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNearestRoadsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof nearestRoads>>> = ({ signal }) => nearestRoads(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof nearestRoads>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NearestRoadsQueryResult = NonNullable<Awaited<ReturnType<typeof nearestRoads>>>
export type NearestRoadsQueryError = AxiosError<NearestRoadsErrorResponse>


export function useNearestRoads<TData = Awaited<ReturnType<typeof nearestRoads>>, TError = AxiosError<NearestRoadsErrorResponse>>(
 params: NearestRoadsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof nearestRoads>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof nearestRoads>>,
          TError,
          Awaited<ReturnType<typeof nearestRoads>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNearestRoads<TData = Awaited<ReturnType<typeof nearestRoads>>, TError = AxiosError<NearestRoadsErrorResponse>>(
 params: NearestRoadsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof nearestRoads>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof nearestRoads>>,
          TError,
          Awaited<ReturnType<typeof nearestRoads>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNearestRoads<TData = Awaited<ReturnType<typeof nearestRoads>>, TError = AxiosError<NearestRoadsErrorResponse>>(
 params: NearestRoadsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof nearestRoads>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useNearestRoads<TData = Awaited<ReturnType<typeof nearestRoads>>, TError = AxiosError<NearestRoadsErrorResponse>>(
 params: NearestRoadsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof nearestRoads>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNearestRoadsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



