/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  TimeZoneResponse,
  TimezoneParams
} from './model';






/**
 * The Time Zone API provides a simple interface to request the time zone for locations on the surface of the earth, as well as the time offset from UTC for each of those locations. You request the time zone information for a specific latitude/longitude pair and date. The API returns the name of that time zone, the time offset from UTC, and the daylight savings offset.

 */
export const timezone = (
    params: TimezoneParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TimeZoneResponse>> => {
    
    
    return axios.get(
      `/maps/api/timezone/json`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getTimezoneQueryKey = (params?: TimezoneParams,) => {
    return [
    `/maps/api/timezone/json`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getTimezoneQueryOptions = <TData = Awaited<ReturnType<typeof timezone>>, TError = AxiosError<unknown>>(params: TimezoneParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof timezone>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTimezoneQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof timezone>>> = ({ signal }) => timezone(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof timezone>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TimezoneQueryResult = NonNullable<Awaited<ReturnType<typeof timezone>>>
export type TimezoneQueryError = AxiosError<unknown>


export function useTimezone<TData = Awaited<ReturnType<typeof timezone>>, TError = AxiosError<unknown>>(
 params: TimezoneParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof timezone>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof timezone>>,
          TError,
          Awaited<ReturnType<typeof timezone>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTimezone<TData = Awaited<ReturnType<typeof timezone>>, TError = AxiosError<unknown>>(
 params: TimezoneParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof timezone>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof timezone>>,
          TError,
          Awaited<ReturnType<typeof timezone>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTimezone<TData = Awaited<ReturnType<typeof timezone>>, TError = AxiosError<unknown>>(
 params: TimezoneParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof timezone>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTimezone<TData = Awaited<ReturnType<typeof timezone>>, TError = AxiosError<unknown>>(
 params: TimezoneParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof timezone>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTimezoneQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



