/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */
import type { DirectionsTransitVehicleType } from './directionsTransitVehicleType';

export interface DirectionsTransitVehicle {
  /** Contains the URL for an icon associated with this vehicle type. */
  icon?: string;
  /** Contains the URL for the icon associated with this vehicle type, based on the local transport signage. */
  local_icon?: string;
  /** The name of this vehicle, capitalized. */
  name: string;
  /** The type of vehicle used.

* `BUS` -	Bus.
* `CABLE_CAR` -	A vehicle that operates on a cable, usually on the ground. Aerial cable cars may be of the type GONDOLA_LIFT.
* `COMMUTER_TRAIN` -	Commuter rail.
* `FERRY` -	Ferry.
* `FUNICULAR` -	A vehicle that is pulled up a steep incline by a cable. A Funicular typically consists of two cars, with each car acting as a counterweight for the other.
* `GONDOLA_LIFT` -	An aerial cable car.
* `HEAVY_RAIL` -	Heavy rail.
* `HIGH_SPEED_TRAIN` -	High speed train.
* `INTERCITY_BUS` -	Intercity bus.
* `LONG_DISTANCE_TRAIN` -	Long distance train.
* `METRO_RAIL` -	Light rail transit.
* `MONORAIL` -	Monorail.
* `OTHER` -	All other vehicles will return this type.
* `RAIL` -	Rail.
* `SHARE_TAXI` -	Share taxi is a kind of bus with the ability to drop off and pick up passengers anywhere on its route.
* `SUBWAY` -	Underground light rail.
* `TRAM` -	Above ground light rail.
* `TROLLEYBUS` -	Trolleybus.
 */
  type: DirectionsTransitVehicleType;
}
