/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

export interface DirectionsTransitAgency {
  /** The name of this transit agency. */
  name?: string;
  /** The transit agency's phone number. */
  phone?: string;
  /** The transit agency's URL. */
  url?: string;
}
