/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

/**
 * Indicates the status code resulting from the geocoding operation. This field may contain the following values.
 */
export type DirectionsGeocodedWaypointGeocoderStatus = typeof DirectionsGeocodedWaypointGeocoderStatus[keyof typeof DirectionsGeocodedWaypointGeocoderStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DirectionsGeocodedWaypointGeocoderStatus = {
  OK: 'OK',
  ZERO_RESULTS: 'ZERO_RESULTS',
} as const;
