/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */
import type { DirectionsLeg } from './directionsLeg';
import type { Bounds } from './bounds';
import type { DirectionsPolyline } from './directionsPolyline';
import type { Fare } from './fare';

/**
 * Routes consist of nested `legs` and `steps`.
 */
export interface DirectionsRoute {
  /** An array which contains information about a leg of the route, between two locations within the given route. A separate leg will be present for each waypoint or destination specified. (A route with no waypoints will contain exactly one leg within the legs array.) Each leg consists of a series of steps. */
  legs: DirectionsLeg[];
  /** Contains the viewport bounding box of the `overview_polyline`. */
  bounds: Bounds;
  /** Contains an array of warnings to be displayed when showing these directions. You must handle and display these warnings yourself. */
  copyrights: string;
  /** Contains a short textual description for the route, suitable for naming and disambiguating the route from alternatives. */
  summary: string;
  /** An array indicating the order of any waypoints in the calculated route. This waypoints may be reordered if the request was passed optimize:true within its waypoints parameter. */
  waypoint_order: number[];
  /** Contains an array of warnings to be displayed when showing these directions. You must handle and display these warnings yourself. */
  warnings: string[];
  /** Contains an object that holds an encoded polyline representation of the route. This polyline is an approximate (smoothed) path of the resulting directions. */
  overview_polyline: DirectionsPolyline;
  /** If present, contains the total fare (that is, the total ticket costs) on this route. This property is only returned for transit requests and only for routes where fare information is available for all transit legs. */
  fare?: Fare;
}
