/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */
import type { TimeZoneTextValueObject } from './timeZoneTextValueObject';
import type { TextValueObject } from './textValueObject';
import type { LatLngLiteral } from './latLngLiteral';
import type { DirectionsStep } from './directionsStep';
import type { DirectionsTrafficSpeedEntry } from './directionsTrafficSpeedEntry';
import type { DirectionsViaWaypoint } from './directionsViaWaypoint';

export interface DirectionsLeg {
  /** Contains the estimated time of arrival for this leg. This property is only returned for transit directions. */
  arrival_time?: TimeZoneTextValueObject;
  /** Contains the estimated time of departure for this leg, specified as a Time object. The `departure_time` is only available for transit directions. */
  departure_time?: TimeZoneTextValueObject;
  /** The total distance covered by this leg. */
  distance?: TextValueObject;
  /** The total duration of this leg. */
  duration?: TextValueObject;
  /** Indicates the total duration of this leg. This value is an estimate of the time in traffic based on current and historical traffic conditions. See the `traffic_model` request parameter for the options you can use to request that the returned value is optimistic, pessimistic, or a best-guess estimate. The duration in traffic is returned only if all of the following are true:

* The request does not include stopover waypoints. If the request includes waypoints, they must be prefixed with `via:` to avoid stopovers.
* The request is specifically for driving directions—the mode parameter is set to `driving`.
* The request includes a `departure_time` parameter.
* Traffic conditions are available for the requested route.
 */
  duration_in_traffic?: TextValueObject;
  /** Contains the human-readable address (typically a street address) from reverse geocoding the `end_location` of this leg. This content is meant to be read as-is. Do not programmatically parse the formatted address. */
  end_address: string;
  /** The latitude/longitude coordinates of the given destination of this leg. Because the Directions API calculates directions between locations by using the nearest transportation option (usually a road) at the start and end points, `end_location` may be different than the provided destination of this leg if, for example, a road is not near the destination. */
  end_location: LatLngLiteral;
  /** Contains the human-readable address (typically a street address) resulting from reverse geocoding the `start_location` of this leg. This content is meant to be read as-is. Do not programmatically parse the formatted address. */
  start_address: string;
  /** The latitude/longitude coordinates of the origin of this leg. Because the Directions API calculates directions between locations by using the nearest transportation option (usually a road) at the start and end points, `start_location` may be different than the provided origin of this leg if, for example, a road is not near the origin. */
  start_location: LatLngLiteral;
  /** An array of steps denoting information about each separate step of the leg of the journey. */
  steps: DirectionsStep[];
  /**
   * Information about traffic speed along the leg.
   * @deprecated
   */
  traffic_speed_entry: DirectionsTrafficSpeedEntry[];
  /** The locations of via waypoints along this leg. */
  via_waypoint: DirectionsViaWaypoint[];
}
