/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */
import type { LatLngLiteral } from './latLngLiteral';

export interface DirectionsTransitStop {
  /** The location of the stop. */
  location: LatLngLiteral;
  /** The name of the transit stop. */
  name: string;
}
