/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

/**
 * @deprecated
 */
export interface DirectionsTrafficSpeedEntry {
  /** The current traffic/speed conditions on this portion of a path. */
  speed_category: string;
  /** The offset along the path (in meters) up to which this speed category is valid. */
  offset_meters: number;
}
