/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

/**
 * - `OK` indicates the response contains a valid result.
- `NOT_FOUND` indicates that the origin and/or destination of this pairing could not be geocoded.
- `ZERO_RESULTS` indicates no route could be found between the origin and destination.
- `MAX_ROUTE_LENGTH_EXCEEDED` indicates the requested route is too long and cannot be processed.

 */
export type DistanceMatrixElementStatus = typeof DistanceMatrixElementStatus[keyof typeof DistanceMatrixElementStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DistanceMatrixElementStatus = {
  OK: 'OK',
  NOT_FOUND: 'NOT_FOUND',
  ZERO_RESULTS: 'ZERO_RESULTS',
  MAX_ROUTE_LENGTH_EXCEEDED: 'MAX_ROUTE_LENGTH_EXCEEDED',
} as const;
