/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

export type DistancematrixUnitsParameter = typeof DistancematrixUnitsParameter[keyof typeof DistancematrixUnitsParameter];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DistancematrixUnitsParameter = {
  imperial: 'imperial',
  metric: 'metric',
} as const;
