/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

/**
 * An array of comma separated `latitude,longitude` strings.
 */
export type ElevationPathParameter = string[];
