/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */
import type { LatLngLiteral } from './latLngLiteral';

export interface ElevationResult {
  /** The elevation of the location in meters. */
  elevation: number;
  /** The value indicating the maximum distance between data points from which the elevation was interpolated, in meters. This property will be missing if the resolution is not known. Note that elevation data becomes more coarse (larger resolution values) when multiple points are passed. To obtain the most accurate elevation value for a point, it should be queried independently. */
  resolution?: number;
  /** A location element of the position for which elevation data is being computed. Note that for path requests, the set of location elements will contain the sampled points along the path. */
  location: LatLngLiteral;
}
