/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */
import type { ElevationLocationsParameter } from './elevationLocationsParameter';
import type { ElevationPathParameter } from './elevationPathParameter';
import type { ElevationSamplesParameter } from './elevationSamplesParameter';

export type ElevationParams = {
/**
 * An array of comma separated {latitude,longitude} strings.
 */
locations?: ElevationLocationsParameter;
/**
 * An array of comma separated {latitude,longitude} strings.
 */
path?: ElevationPathParameter;
/**
 * Required if path parameter is set.
 */
samples?: ElevationSamplesParameter;
};
