/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */
import type { ErrorDetailMetadata } from './errorDetailMetadata';
import type { FieldViolation } from './fieldViolation';

export interface ErrorDetail {
  /** The type of error. */
  '@type'?: string;
  /** A short description of the error. */
  message?: string;
  /** A reason for the error. */
  reason?: string;
  /** The domain in which the error occurred. */
  domain?: string;
  /** Additional metadata about the error. */
  metadata?: ErrorDetailMetadata;
  /** A list of field violations. */
  fieldViolations?: FieldViolation[];
}
