/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */
import type { ErrorDetail } from './errorDetail';

export interface ErrorObject {
  /** This is the same as the HTTP status of the response. */
  code: number;
  /** A short description of the error. */
  message: string;
  /** A list of errors which occurred. Each error contains an identifier for the type of error and a short description. */
  errors: ErrorDetail[];
  /** A status code that indicates the error type. */
  status?: string;
  /** Additional details about the error. */
  details?: ErrorDetail[];
}
