/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

export interface FieldViolation {
  /** The name of the invalid field. */
  field: string;
  /** A short description of the error. */
  description: string;
}
