/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */
import type { PlusCode } from './plusCode';
import type { GeocodingResult } from './geocodingResult';
import type { GeocodingStatus } from './geocodingStatus';

export interface GeocodingResponse {
  /** An encoded location reference, derived from latitude and longitude coordinates, that represents an area: 1/8000th of a degree by 1/8000th of a degree (about 14m x 14m at the equator) or smaller. Plus codes can be used as a replacement for street addresses in places where they do not exist (where buildings are not numbered or streets are not named). See [Open Location Code](https://en.wikipedia.org/wiki/Open_Location_Code) and [plus codes](https://plus.codes/).
 */
  plus_code?: PlusCode;
  results: GeocodingResult[];
  status: GeocodingStatus;
  /** A short description of the error. */
  error_message?: string;
}
