/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

/**
 * The bounding box of the viewport within which to bias geocode results more prominently. This parameter will only influence, not fully restrict, results from the geocoder.
 */
export type GeocodeBoundsParameter = string[];
