/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

export type GeocodeLocationTypeParameterItem = typeof GeocodeLocationTypeParameterItem[keyof typeof GeocodeLocationTypeParameterItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GeocodeLocationTypeParameterItem = {
  APPROXIMATE: 'APPROXIMATE',
  GEOMETRIC_CENTER: 'GEOMETRIC_CENTER',
  RANGE_INTERPOLATED: 'RANGE_INTERPOLATED',
  ROOFTOP: 'ROOFTOP',
} as const;
