/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

/**
 * A textual identifier that uniquely identifies a place, returned from a [Place Search](https://developers.google.com/maps/documentation/places/web-service/search).
For more information about place IDs, see the [place ID overview](https://developers.google.com/maps/documentation/places/web-service/place-id).

 */
export type GeocodePlaceIdParameter = string;
