/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

export type LanguageParameter = typeof LanguageParameter[keyof typeof LanguageParameter];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LanguageParameter = {
  ar: 'ar',
  bg: 'bg',
  bn: 'bn',
  ca: 'ca',
  cs: 'cs',
  da: 'da',
  de: 'de',
  el: 'el',
  en: 'en',
  'en-AU': 'en-AU',
  'en-GB': 'en-GB',
  es: 'es',
  eu: 'eu',
  fa: 'fa',
  fi: 'fi',
  fil: 'fil',
  fr: 'fr',
  gl: 'gl',
  gu: 'gu',
  hi: 'hi',
  hr: 'hr',
  hu: 'hu',
  id: 'id',
  it: 'it',
  iw: 'iw',
  ja: 'ja',
  kn: 'kn',
  ko: 'ko',
  lt: 'lt',
  lv: 'lv',
  ml: 'ml',
  mr: 'mr',
  nl: 'nl',
  no: 'no',
  pl: 'pl',
  pt: 'pt',
  'pt-BR': 'pt-BR',
  'pt-PT': 'pt-PT',
  ro: 'ro',
  ru: 'ru',
  sk: 'sk',
  sl: 'sl',
  sr: 'sr',
  sv: 'sv',
  ta: 'ta',
  te: 'te',
  th: 'th',
  tl: 'tl',
  tr: 'tr',
  uk: 'uk',
  vi: 'vi',
  'zh-CN': 'zh-CN',
  'zh-TW': 'zh-TW',
} as const;
