/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */
import type { SnappedPoint } from './snappedPoint';

export interface NearestRoadsResponse {
  /** An array of snapped points. Sometimes containing several snapped points for the same point with differing placeId or location. */
  snappedPoints?: SnappedPoint[];
}
