/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

/**
 * Equivalent to `keyword`. Values in this field are combined with values in the `keyword` field and passed as part of the same search string.

 * @deprecated
 */
export type PlacesNameParameter = string;
