/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

export type PlacesMaxpriceParameter = typeof PlacesMaxpriceParameter[keyof typeof PlacesMaxpriceParameter];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlacesMaxpriceParameter = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
} as const;
