/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

/**
 * The text string on which to search, for example: "restaurant" or "123 Main Street". This must be a place name, address, or category of establishments.
Any other types of input can generate errors and are not guaranteed to return valid results. The Google Places service will return candidate matches
based on this string and order the results based on their perceived relevance.

Explicitly including location information using this parameter may conflict with the location, radius, and rankby parameters, causing unexpected results.

If this parameter is omitted, places with a business_status of CLOSED_TEMPORARILY or CLOSED_PERMANENTLY will not be returned.

 */
export type PlacesKeywordParameter = string;
