/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

/**
 * A string identifier that uniquely identifies a photo. Photo references are returned from either a Place Search or Place Details request.

 */
export type PlacesPhotoReferenceParameter = string;
