/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

export type PlacesInputtypeParameter = typeof PlacesInputtypeParameter[keyof typeof PlacesInputtypeParameter];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlacesInputtypeParameter = {
  textquery: 'textquery',
  phonenumber: 'phonenumber',
} as const;
