/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

export interface PlaceAutocompleteTerm {
  /** The text of the term. */
  value: string;
  /** Defines the start position of this term in the description, measured in Unicode characters */
  offset: number;
}
