/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */
import type { Place } from './place';
import type { PlacesSearchStatus } from './placesSearchStatus';

export interface PlacesFindPlaceFromTextResponse {
  /** Contains an array of Place candidates.
<div class="caution">Place Search requests return a subset of the fields that are returned by Place Details requests. If the field you want is not returned by Place Search, you can use Place Search to get a place_id, then use that Place ID to make a Place Details request.</div>
 */
  candidates: Place[];
  /** Contains the status of the request, and may contain debugging information to help you track down why the request failed. */
  status: PlacesSearchStatus;
  /** When the service returns a status code other than `OK<`, there may be an additional `error_message` field within the response object. This field contains more detailed information about thereasons behind the given status code. This field is not always returned, and its content is subject to change.
 */
  error_message?: string;
  /** When the service returns additional information about the request specification, there may be an additional `info_messages` field within the response object. This field is only returned for successful requests. It may not always be returned, and its content is subject to change.
 */
  info_messages?: string[];
}
