/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

/**
 * The sorting method to use when returning reviews. Can be set to `most_relevant` (default) or `newest`.

- For `most_relevant` (default), reviews are sorted by relevance; the service will bias the results to return reviews originally written in the preferred language.
- For `newest`, reviews are sorted in chronological order; the preferred language does not affect the sort order.

Google recommends that you display how the reviews are being sorted to the end user.

 */
export type PlacesReviewsortParameter = string;
