/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

export interface PlaceAutocompleteMatchedSubstring {
  /** Length of the matched substring in the prediction result text. */
  length: number;
  /** Start location of the matched substring in the prediction result text. */
  offset: number;
}
