/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

/**
 * The point around which to retrieve place information. This must be specified as `latitude,longitude`.

 */
export type PlacesLocationRequiredParameter = string;
