/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

export type PlacesRankbyParameter = typeof PlacesRankbyParameter[keyof typeof PlacesRankbyParameter];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlacesRankbyParameter = {
  prominence: 'prominence',
  distance: 'distance',
} as const;
