/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */
import type { PlaceAutocompleteMatchedSubstring } from './placeAutocompleteMatchedSubstring';
import type { PlaceAutocompleteStructuredFormat } from './placeAutocompleteStructuredFormat';
import type { PlaceAutocompleteTerm } from './placeAutocompleteTerm';

export interface PlaceAutocompletePrediction {
  /** Contains the human-readable name for the returned result. For `establishment` results, this is usually the business name. This content is meant to be read as-is. Do not programmatically parse the formatted address. */
  description: string;
  /** A list of substrings that describe the location of the entered term in the prediction result text, so that the term can be highlighted if desired. */
  matched_substrings: PlaceAutocompleteMatchedSubstring[];
  /** A textual identifier that uniquely identifies a place. To retrieve information about the place, pass this identifier in the placeId field of a Places API request. For more information about place IDs, see the [Place IDs](https://developers.google.com/maps/documentation/places/web-service/place-id) overview. */
  place_id?: string;
  /**
   * See place_id.
   * @deprecated
   */
  reference?: string;
  /** Provides pre-formatted text that can be shown in your autocomplete results. This content is meant to be read as-is. Do not programmatically parse the formatted address. */
  structured_formatting: PlaceAutocompleteStructuredFormat;
  /** Contains an array of terms identifying each section of the returned description (a section of the description is generally terminated with a comma). Each entry in the array has a `value` field, containing the text of the term, and an `offset` field, defining the start position of this term in the description, measured in Unicode characters. */
  terms: PlaceAutocompleteTerm[];
  /** Contains an array of types that apply to this place. For example: `[ "political", "locality" ]` or `[ "establishment", "geocode", "beauty_salon" ]`. The array can contain multiple values. Learn more about [Place types](https://developers.google.com/maps/documentation/places/web-service/supported_types).
 */
  types?: string[];
  /** The straight-line distance in meters from the origin. This field is only returned for requests made with an `origin`. */
  distance_meters?: number;
}
