/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

/**
 * Returns up to 20 results from a previously run search. Setting a `pagetoken` parameter will execute a search with the same parameters used previously — all parameters other than pagetoken will be ignored.

 */
export type PlacesPagetokenParameter = string;
