/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

/**
 * Defines the distance (in meters) within which to return place results. You may bias results to a specified circle by passing a `location` and a `radius` parameter. Doing so instructs the Places service to _prefer_ showing results within that circle; results outside of the defined area may still be displayed.

The radius will automatically be clamped to a maximum value depending on the type of search and other parameters.

* Autocomplete: 50,000 meters
* Nearby Search: 
  * with `keyword` or `name`: 50,000 meters
  * without `keyword` or `name`
    * Up to 50,000 meters, adjusted dynamically based on area density, independent of `rankby` parameter.
    * When using `rankby=distance`, the radius parameter will not be accepted, and will result in an `INVALID_REQUEST`.
* Query Autocomplete: 50,000 meters
* Text Search: 50,000 meters

 */
export type PlacesRadiusParameter = number;
