/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

/**
 * A specific panorama ID. These are generally stable, though panoramas may change ID over time as imagery is refreshed.

 */
export type StreetviewPanoParameter = string;
