/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

export type StreetviewSourceParameter = typeof StreetviewSourceParameter[keyof typeof StreetviewSourceParameter];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StreetviewSourceParameter = {
  default: 'default',
  outdoor: 'outdoor',
} as const;
