/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

/**
 * An object containing a numeric value and its formatted text representation.
 */
export interface TextValueObject {
  /** String value. */
  text: string;
  /** Numeric value. */
  value: number;
}
