/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

/**
 * An object containing Unix time, a time zone, and its formatted text representation.
 */
export interface TimeZoneTextValueObject {
  /** The time specified as a string in the time zone. */
  text: string;
  /** The time specified as Unix time, or seconds since midnight, January 1, 1970 UTC. */
  value: number;
  /** Contains the time zone. The value is the name of the time zone as defined in the [IANA Time Zone Database](http://www.iana.org/time-zones), e.g. "America/New_York". */
  time_zone: string;
}
