/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

/**
 * A comma-separated latitude,longitude tuple, `location=39.6034810,-119.6822510`, representing the location to look up.

 */
export type TimezoneLocationParameter = string;
