/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

export type TrafficModelParameter = typeof TrafficModelParameter[keyof typeof TrafficModelParameter];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TrafficModelParameter = {
  best_guess: 'best_guess',
  pessimistic: 'pessimistic',
  optimistic: 'optimistic',
} as const;
