/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

export type TransitRoutingPreferenceParameter = typeof TransitRoutingPreferenceParameter[keyof typeof TransitRoutingPreferenceParameter];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransitRoutingPreferenceParameter = {
  less_walking: 'less_walking',
  fewer_transfers: 'fewer_transfers',
} as const;
