/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

/**
 * Specifies one or more preferred modes of transit. This parameter may only be specified for transit directions. The parameter supports the following arguments:
* `bus` indicates that the calculated route should prefer travel by bus.
* `subway` indicates that the calculated route should prefer travel by subway.
* `train` indicates that the calculated route should prefer travel by train.
* `tram` indicates that the calculated route should prefer travel by tram and light rail.
* `rail` indicates that the calculated route should prefer travel by train, tram, light rail, and subway. This is equivalent to `transit_mode=train|tram|subway`.

 */
export type TransitModeParameter = string;
