/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Google Maps Platform
 * API Specification for Google Maps Platform
 * OpenAPI spec version: 1.22.3
 */

/**
 * - `DRIVING` (default) indicates calculation using the road network.
- `BICYCLING` requests calculation for bicycling via bicycle paths & preferred streets (where available).
- `TRANSIT` requests calculation via public transit routes (where available). 
- `WALKING` requests calculation for walking via pedestrian paths & sidewalks (where available).

 */
export type TravelMode = typeof TravelMode[keyof typeof TravelMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TravelMode = {
  DRIVING: 'DRIVING',
  BICYCLING: 'BICYCLING',
  TRANSIT: 'TRANSIT',
  WALKING: 'WALKING',
} as const;
