/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';






export const applicationControllerCreateApplication = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.post(
      `/application`,undefined,options
    );
  }



export const getApplicationControllerCreateApplicationMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationControllerCreateApplication>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof applicationControllerCreateApplication>>, TError,void, TContext> => {

const mutationKey = ['applicationControllerCreateApplication'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof applicationControllerCreateApplication>>, void> = () => {
          

          return  applicationControllerCreateApplication(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApplicationControllerCreateApplicationMutationResult = NonNullable<Awaited<ReturnType<typeof applicationControllerCreateApplication>>>
    
    export type ApplicationControllerCreateApplicationMutationError = AxiosError<unknown>

    export const useApplicationControllerCreateApplication = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applicationControllerCreateApplication>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof applicationControllerCreateApplication>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getApplicationControllerCreateApplicationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    