/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ContactDto
} from './model';

import { customInstance } from '../utils/custom-axios';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const contactControllerContact = (
    contactDto: ContactDto,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/contact`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: contactDto, signal
    },
      options);
    }
  


export const getContactControllerContactMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof contactControllerContact>>, TError,{data: ContactDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof contactControllerContact>>, TError,{data: ContactDto}, TContext> => {

const mutationKey = ['contactControllerContact'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof contactControllerContact>>, {data: ContactDto}> = (props) => {
          const {data} = props ?? {};

          return  contactControllerContact(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ContactControllerContactMutationResult = NonNullable<Awaited<ReturnType<typeof contactControllerContact>>>
    export type ContactControllerContactMutationBody = ContactDto
    export type ContactControllerContactMutationError = unknown

    export const useContactControllerContact = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof contactControllerContact>>, TError,{data: ContactDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof contactControllerContact>>,
        TError,
        {data: ContactDto},
        TContext
      > => {

      const mutationOptions = getContactControllerContactMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    