/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateListingDto,
  ErrorDto,
  Listing,
  Step2ListingDto,
  Step3ListingDto,
  Step4ListingDto
} from './model';






export const listingsControllerCreateDraft = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    
    
    return axios.post(
      `/listings/draft`,undefined,{
        responseType: 'text',
    ...options,}
    );
  }



export const getListingsControllerCreateDraftMutationOptions = <TError = AxiosError<ErrorDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listingsControllerCreateDraft>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof listingsControllerCreateDraft>>, TError,void, TContext> => {

const mutationKey = ['listingsControllerCreateDraft'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof listingsControllerCreateDraft>>, void> = () => {
          

          return  listingsControllerCreateDraft(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ListingsControllerCreateDraftMutationResult = NonNullable<Awaited<ReturnType<typeof listingsControllerCreateDraft>>>
    
    export type ListingsControllerCreateDraftMutationError = AxiosError<ErrorDto>

    export const useListingsControllerCreateDraft = <TError = AxiosError<ErrorDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listingsControllerCreateDraft>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof listingsControllerCreateDraft>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getListingsControllerCreateDraftMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listingsControllerCreateStep1 = (
    id: string,
    createListingDto: CreateListingDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Listing>> => {
    
    
    return axios.patch(
      `/listings/${id}/createStep1`,
      createListingDto,options
    );
  }



export const getListingsControllerCreateStep1MutationOptions = <TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listingsControllerCreateStep1>>, TError,{id: string;data: CreateListingDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof listingsControllerCreateStep1>>, TError,{id: string;data: CreateListingDto}, TContext> => {

const mutationKey = ['listingsControllerCreateStep1'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof listingsControllerCreateStep1>>, {id: string;data: CreateListingDto}> = (props) => {
          const {id,data} = props ?? {};

          return  listingsControllerCreateStep1(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ListingsControllerCreateStep1MutationResult = NonNullable<Awaited<ReturnType<typeof listingsControllerCreateStep1>>>
    export type ListingsControllerCreateStep1MutationBody = CreateListingDto
    export type ListingsControllerCreateStep1MutationError = AxiosError<ErrorDto | ErrorDto | ErrorDto>

    export const useListingsControllerCreateStep1 = <TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listingsControllerCreateStep1>>, TError,{id: string;data: CreateListingDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof listingsControllerCreateStep1>>,
        TError,
        {id: string;data: CreateListingDto},
        TContext
      > => {

      const mutationOptions = getListingsControllerCreateStep1MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listingsControllerCreateStep2 = (
    id: string,
    step2ListingDto: Step2ListingDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Listing>> => {
    
    
    return axios.patch(
      `/listings/${id}/createStep2`,
      step2ListingDto,options
    );
  }



export const getListingsControllerCreateStep2MutationOptions = <TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listingsControllerCreateStep2>>, TError,{id: string;data: Step2ListingDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof listingsControllerCreateStep2>>, TError,{id: string;data: Step2ListingDto}, TContext> => {

const mutationKey = ['listingsControllerCreateStep2'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof listingsControllerCreateStep2>>, {id: string;data: Step2ListingDto}> = (props) => {
          const {id,data} = props ?? {};

          return  listingsControllerCreateStep2(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ListingsControllerCreateStep2MutationResult = NonNullable<Awaited<ReturnType<typeof listingsControllerCreateStep2>>>
    export type ListingsControllerCreateStep2MutationBody = Step2ListingDto
    export type ListingsControllerCreateStep2MutationError = AxiosError<ErrorDto | ErrorDto | ErrorDto>

    export const useListingsControllerCreateStep2 = <TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listingsControllerCreateStep2>>, TError,{id: string;data: Step2ListingDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof listingsControllerCreateStep2>>,
        TError,
        {id: string;data: Step2ListingDto},
        TContext
      > => {

      const mutationOptions = getListingsControllerCreateStep2MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listingsControllerCreateStep3 = (
    id: string,
    step3ListingDto: Step3ListingDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Listing>> => {
    
    
    return axios.patch(
      `/listings/${id}/createStep3`,
      step3ListingDto,options
    );
  }



export const getListingsControllerCreateStep3MutationOptions = <TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listingsControllerCreateStep3>>, TError,{id: string;data: Step3ListingDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof listingsControllerCreateStep3>>, TError,{id: string;data: Step3ListingDto}, TContext> => {

const mutationKey = ['listingsControllerCreateStep3'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof listingsControllerCreateStep3>>, {id: string;data: Step3ListingDto}> = (props) => {
          const {id,data} = props ?? {};

          return  listingsControllerCreateStep3(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ListingsControllerCreateStep3MutationResult = NonNullable<Awaited<ReturnType<typeof listingsControllerCreateStep3>>>
    export type ListingsControllerCreateStep3MutationBody = Step3ListingDto
    export type ListingsControllerCreateStep3MutationError = AxiosError<ErrorDto | ErrorDto | ErrorDto>

    export const useListingsControllerCreateStep3 = <TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listingsControllerCreateStep3>>, TError,{id: string;data: Step3ListingDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof listingsControllerCreateStep3>>,
        TError,
        {id: string;data: Step3ListingDto},
        TContext
      > => {

      const mutationOptions = getListingsControllerCreateStep3MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listingsControllerCreateStep4 = (
    id: string,
    step4ListingDto: Step4ListingDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.patch(
      `/listings/${id}/createStep4`,
      step4ListingDto,options
    );
  }



export const getListingsControllerCreateStep4MutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listingsControllerCreateStep4>>, TError,{id: string;data: Step4ListingDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof listingsControllerCreateStep4>>, TError,{id: string;data: Step4ListingDto}, TContext> => {

const mutationKey = ['listingsControllerCreateStep4'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof listingsControllerCreateStep4>>, {id: string;data: Step4ListingDto}> = (props) => {
          const {id,data} = props ?? {};

          return  listingsControllerCreateStep4(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ListingsControllerCreateStep4MutationResult = NonNullable<Awaited<ReturnType<typeof listingsControllerCreateStep4>>>
    export type ListingsControllerCreateStep4MutationBody = Step4ListingDto
    export type ListingsControllerCreateStep4MutationError = AxiosError<unknown>

    export const useListingsControllerCreateStep4 = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listingsControllerCreateStep4>>, TError,{id: string;data: Step4ListingDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof listingsControllerCreateStep4>>,
        TError,
        {id: string;data: Step4ListingDto},
        TContext
      > => {

      const mutationOptions = getListingsControllerCreateStep4MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listingsControllerPublish = (
    id: string,
    createListingDto: CreateListingDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Listing>> => {
    
    
    return axios.post(
      `/listings/${id}/publish`,
      createListingDto,options
    );
  }



export const getListingsControllerPublishMutationOptions = <TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listingsControllerPublish>>, TError,{id: string;data: CreateListingDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof listingsControllerPublish>>, TError,{id: string;data: CreateListingDto}, TContext> => {

const mutationKey = ['listingsControllerPublish'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof listingsControllerPublish>>, {id: string;data: CreateListingDto}> = (props) => {
          const {id,data} = props ?? {};

          return  listingsControllerPublish(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ListingsControllerPublishMutationResult = NonNullable<Awaited<ReturnType<typeof listingsControllerPublish>>>
    export type ListingsControllerPublishMutationBody = CreateListingDto
    export type ListingsControllerPublishMutationError = AxiosError<ErrorDto | ErrorDto | ErrorDto>

    export const useListingsControllerPublish = <TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listingsControllerPublish>>, TError,{id: string;data: CreateListingDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof listingsControllerPublish>>,
        TError,
        {id: string;data: CreateListingDto},
        TContext
      > => {

      const mutationOptions = getListingsControllerPublishMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listingsControllerDeleteListing = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Listing>> => {
    
    
    return axios.delete(
      `/listings/${id}`,options
    );
  }



export const getListingsControllerDeleteListingMutationOptions = <TError = AxiosError<ErrorDto | ErrorDto | ErrorDto | ErrorDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listingsControllerDeleteListing>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof listingsControllerDeleteListing>>, TError,{id: string}, TContext> => {

const mutationKey = ['listingsControllerDeleteListing'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof listingsControllerDeleteListing>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  listingsControllerDeleteListing(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ListingsControllerDeleteListingMutationResult = NonNullable<Awaited<ReturnType<typeof listingsControllerDeleteListing>>>
    
    export type ListingsControllerDeleteListingMutationError = AxiosError<ErrorDto | ErrorDto | ErrorDto | ErrorDto>

    export const useListingsControllerDeleteListing = <TError = AxiosError<ErrorDto | ErrorDto | ErrorDto | ErrorDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listingsControllerDeleteListing>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof listingsControllerDeleteListing>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getListingsControllerDeleteListingMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listingsControllerGetById = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Listing>> => {
    
    
    return axios.get(
      `/listings/${id}`,options
    );
  }




export const getListingsControllerGetByIdQueryKey = (id?: string,) => {
    return [
    `/listings/${id}`
    ] as const;
    }

    
export const getListingsControllerGetByIdQueryOptions = <TData = Awaited<ReturnType<typeof listingsControllerGetById>>, TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listingsControllerGetById>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListingsControllerGetByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listingsControllerGetById>>> = ({ signal }) => listingsControllerGetById(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listingsControllerGetById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListingsControllerGetByIdQueryResult = NonNullable<Awaited<ReturnType<typeof listingsControllerGetById>>>
export type ListingsControllerGetByIdQueryError = AxiosError<ErrorDto | ErrorDto | ErrorDto>


export function useListingsControllerGetById<TData = Awaited<ReturnType<typeof listingsControllerGetById>>, TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listingsControllerGetById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listingsControllerGetById>>,
          TError,
          Awaited<ReturnType<typeof listingsControllerGetById>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListingsControllerGetById<TData = Awaited<ReturnType<typeof listingsControllerGetById>>, TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listingsControllerGetById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listingsControllerGetById>>,
          TError,
          Awaited<ReturnType<typeof listingsControllerGetById>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListingsControllerGetById<TData = Awaited<ReturnType<typeof listingsControllerGetById>>, TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listingsControllerGetById>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListingsControllerGetById<TData = Awaited<ReturnType<typeof listingsControllerGetById>>, TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listingsControllerGetById>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListingsControllerGetByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const listingsControllerMyListings = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Listing[]>> => {
    
    
    return axios.get(
      `/listings/mine`,options
    );
  }




export const getListingsControllerMyListingsQueryKey = () => {
    return [
    `/listings/mine`
    ] as const;
    }

    
export const getListingsControllerMyListingsQueryOptions = <TData = Awaited<ReturnType<typeof listingsControllerMyListings>>, TError = AxiosError<ErrorDto | ErrorDto>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listingsControllerMyListings>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListingsControllerMyListingsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listingsControllerMyListings>>> = ({ signal }) => listingsControllerMyListings({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listingsControllerMyListings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListingsControllerMyListingsQueryResult = NonNullable<Awaited<ReturnType<typeof listingsControllerMyListings>>>
export type ListingsControllerMyListingsQueryError = AxiosError<ErrorDto | ErrorDto>


export function useListingsControllerMyListings<TData = Awaited<ReturnType<typeof listingsControllerMyListings>>, TError = AxiosError<ErrorDto | ErrorDto>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listingsControllerMyListings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listingsControllerMyListings>>,
          TError,
          Awaited<ReturnType<typeof listingsControllerMyListings>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListingsControllerMyListings<TData = Awaited<ReturnType<typeof listingsControllerMyListings>>, TError = AxiosError<ErrorDto | ErrorDto>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listingsControllerMyListings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listingsControllerMyListings>>,
          TError,
          Awaited<ReturnType<typeof listingsControllerMyListings>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListingsControllerMyListings<TData = Awaited<ReturnType<typeof listingsControllerMyListings>>, TError = AxiosError<ErrorDto | ErrorDto>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listingsControllerMyListings>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListingsControllerMyListings<TData = Awaited<ReturnType<typeof listingsControllerMyListings>>, TError = AxiosError<ErrorDto | ErrorDto>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listingsControllerMyListings>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListingsControllerMyListingsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const listingsControllerGetListing = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Listing>> => {
    
    
    return axios.get(
      `/listings/mine/${id}`,options
    );
  }




export const getListingsControllerGetListingQueryKey = (id?: string,) => {
    return [
    `/listings/mine/${id}`
    ] as const;
    }

    
export const getListingsControllerGetListingQueryOptions = <TData = Awaited<ReturnType<typeof listingsControllerGetListing>>, TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listingsControllerGetListing>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListingsControllerGetListingQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listingsControllerGetListing>>> = ({ signal }) => listingsControllerGetListing(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listingsControllerGetListing>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListingsControllerGetListingQueryResult = NonNullable<Awaited<ReturnType<typeof listingsControllerGetListing>>>
export type ListingsControllerGetListingQueryError = AxiosError<ErrorDto | ErrorDto | ErrorDto>


export function useListingsControllerGetListing<TData = Awaited<ReturnType<typeof listingsControllerGetListing>>, TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listingsControllerGetListing>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listingsControllerGetListing>>,
          TError,
          Awaited<ReturnType<typeof listingsControllerGetListing>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListingsControllerGetListing<TData = Awaited<ReturnType<typeof listingsControllerGetListing>>, TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listingsControllerGetListing>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listingsControllerGetListing>>,
          TError,
          Awaited<ReturnType<typeof listingsControllerGetListing>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListingsControllerGetListing<TData = Awaited<ReturnType<typeof listingsControllerGetListing>>, TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listingsControllerGetListing>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListingsControllerGetListing<TData = Awaited<ReturnType<typeof listingsControllerGetListing>>, TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listingsControllerGetListing>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListingsControllerGetListingQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const listingsControllerGetAllUnverifiedListings = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Listing[]>> => {
    
    
    return axios.get(
      `/listings/allUnverified`,options
    );
  }




export const getListingsControllerGetAllUnverifiedListingsQueryKey = () => {
    return [
    `/listings/allUnverified`
    ] as const;
    }

    
export const getListingsControllerGetAllUnverifiedListingsQueryOptions = <TData = Awaited<ReturnType<typeof listingsControllerGetAllUnverifiedListings>>, TError = AxiosError<ErrorDto | ErrorDto>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listingsControllerGetAllUnverifiedListings>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListingsControllerGetAllUnverifiedListingsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listingsControllerGetAllUnverifiedListings>>> = ({ signal }) => listingsControllerGetAllUnverifiedListings({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listingsControllerGetAllUnverifiedListings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListingsControllerGetAllUnverifiedListingsQueryResult = NonNullable<Awaited<ReturnType<typeof listingsControllerGetAllUnverifiedListings>>>
export type ListingsControllerGetAllUnverifiedListingsQueryError = AxiosError<ErrorDto | ErrorDto>


export function useListingsControllerGetAllUnverifiedListings<TData = Awaited<ReturnType<typeof listingsControllerGetAllUnverifiedListings>>, TError = AxiosError<ErrorDto | ErrorDto>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listingsControllerGetAllUnverifiedListings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listingsControllerGetAllUnverifiedListings>>,
          TError,
          Awaited<ReturnType<typeof listingsControllerGetAllUnverifiedListings>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListingsControllerGetAllUnverifiedListings<TData = Awaited<ReturnType<typeof listingsControllerGetAllUnverifiedListings>>, TError = AxiosError<ErrorDto | ErrorDto>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listingsControllerGetAllUnverifiedListings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listingsControllerGetAllUnverifiedListings>>,
          TError,
          Awaited<ReturnType<typeof listingsControllerGetAllUnverifiedListings>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListingsControllerGetAllUnverifiedListings<TData = Awaited<ReturnType<typeof listingsControllerGetAllUnverifiedListings>>, TError = AxiosError<ErrorDto | ErrorDto>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listingsControllerGetAllUnverifiedListings>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListingsControllerGetAllUnverifiedListings<TData = Awaited<ReturnType<typeof listingsControllerGetAllUnverifiedListings>>, TError = AxiosError<ErrorDto | ErrorDto>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listingsControllerGetAllUnverifiedListings>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListingsControllerGetAllUnverifiedListingsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const listingsControllerVerifyListing = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.patch(
      `/listings/verify/${id}`,undefined,options
    );
  }



export const getListingsControllerVerifyListingMutationOptions = <TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listingsControllerVerifyListing>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof listingsControllerVerifyListing>>, TError,{id: string}, TContext> => {

const mutationKey = ['listingsControllerVerifyListing'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof listingsControllerVerifyListing>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  listingsControllerVerifyListing(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ListingsControllerVerifyListingMutationResult = NonNullable<Awaited<ReturnType<typeof listingsControllerVerifyListing>>>
    
    export type ListingsControllerVerifyListingMutationError = AxiosError<ErrorDto | ErrorDto | ErrorDto>

    export const useListingsControllerVerifyListing = <TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listingsControllerVerifyListing>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof listingsControllerVerifyListing>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getListingsControllerVerifyListingMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    