/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  UploadControllerDownloadParams,
  UploadControllerGetPresignedUrlParams
} from './model';






export const uploadControllerGetPresignedUrl = (
    params: UploadControllerGetPresignedUrlParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.get(
      `/upload/presign`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getUploadControllerGetPresignedUrlQueryKey = (params?: UploadControllerGetPresignedUrlParams,) => {
    return [
    `/upload/presign`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getUploadControllerGetPresignedUrlQueryOptions = <TData = Awaited<ReturnType<typeof uploadControllerGetPresignedUrl>>, TError = AxiosError<unknown>>(params: UploadControllerGetPresignedUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadControllerGetPresignedUrl>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUploadControllerGetPresignedUrlQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof uploadControllerGetPresignedUrl>>> = ({ signal }) => uploadControllerGetPresignedUrl(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof uploadControllerGetPresignedUrl>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UploadControllerGetPresignedUrlQueryResult = NonNullable<Awaited<ReturnType<typeof uploadControllerGetPresignedUrl>>>
export type UploadControllerGetPresignedUrlQueryError = AxiosError<unknown>


export function useUploadControllerGetPresignedUrl<TData = Awaited<ReturnType<typeof uploadControllerGetPresignedUrl>>, TError = AxiosError<unknown>>(
 params: UploadControllerGetPresignedUrlParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadControllerGetPresignedUrl>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof uploadControllerGetPresignedUrl>>,
          TError,
          Awaited<ReturnType<typeof uploadControllerGetPresignedUrl>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUploadControllerGetPresignedUrl<TData = Awaited<ReturnType<typeof uploadControllerGetPresignedUrl>>, TError = AxiosError<unknown>>(
 params: UploadControllerGetPresignedUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadControllerGetPresignedUrl>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof uploadControllerGetPresignedUrl>>,
          TError,
          Awaited<ReturnType<typeof uploadControllerGetPresignedUrl>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUploadControllerGetPresignedUrl<TData = Awaited<ReturnType<typeof uploadControllerGetPresignedUrl>>, TError = AxiosError<unknown>>(
 params: UploadControllerGetPresignedUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadControllerGetPresignedUrl>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUploadControllerGetPresignedUrl<TData = Awaited<ReturnType<typeof uploadControllerGetPresignedUrl>>, TError = AxiosError<unknown>>(
 params: UploadControllerGetPresignedUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadControllerGetPresignedUrl>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUploadControllerGetPresignedUrlQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const uploadControllerDownload = (
    params: UploadControllerDownloadParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.get(
      `/upload/access`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getUploadControllerDownloadQueryKey = (params?: UploadControllerDownloadParams,) => {
    return [
    `/upload/access`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getUploadControllerDownloadQueryOptions = <TData = Awaited<ReturnType<typeof uploadControllerDownload>>, TError = AxiosError<unknown>>(params: UploadControllerDownloadParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadControllerDownload>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUploadControllerDownloadQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof uploadControllerDownload>>> = ({ signal }) => uploadControllerDownload(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof uploadControllerDownload>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UploadControllerDownloadQueryResult = NonNullable<Awaited<ReturnType<typeof uploadControllerDownload>>>
export type UploadControllerDownloadQueryError = AxiosError<unknown>


export function useUploadControllerDownload<TData = Awaited<ReturnType<typeof uploadControllerDownload>>, TError = AxiosError<unknown>>(
 params: UploadControllerDownloadParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadControllerDownload>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof uploadControllerDownload>>,
          TError,
          Awaited<ReturnType<typeof uploadControllerDownload>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUploadControllerDownload<TData = Awaited<ReturnType<typeof uploadControllerDownload>>, TError = AxiosError<unknown>>(
 params: UploadControllerDownloadParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadControllerDownload>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof uploadControllerDownload>>,
          TError,
          Awaited<ReturnType<typeof uploadControllerDownload>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUploadControllerDownload<TData = Awaited<ReturnType<typeof uploadControllerDownload>>, TError = AxiosError<unknown>>(
 params: UploadControllerDownloadParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadControllerDownload>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUploadControllerDownload<TData = Awaited<ReturnType<typeof uploadControllerDownload>>, TError = AxiosError<unknown>>(
 params: UploadControllerDownloadParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadControllerDownload>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUploadControllerDownloadQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



