/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateUserDto,
  ErrorDto,
  SetProfilePicDto,
  SetUsernameDto,
  UserDto
} from './model';






export const usersControllerGetUser = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserDto>> => {
    
    
    return axios.get(
      `/users/${id}`,options
    );
  }




export const getUsersControllerGetUserQueryKey = (id?: string,) => {
    return [
    `/users/${id}`
    ] as const;
    }

    
export const getUsersControllerGetUserQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerGetUser>>, TError = AxiosError<ErrorDto | ErrorDto>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUser>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerGetUserQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetUser>>> = ({ signal }) => usersControllerGetUser(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerGetUserQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerGetUser>>>
export type UsersControllerGetUserQueryError = AxiosError<ErrorDto | ErrorDto>


export function useUsersControllerGetUser<TData = Awaited<ReturnType<typeof usersControllerGetUser>>, TError = AxiosError<ErrorDto | ErrorDto>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetUser>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetUser>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetUser<TData = Awaited<ReturnType<typeof usersControllerGetUser>>, TError = AxiosError<ErrorDto | ErrorDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetUser>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetUser>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetUser<TData = Awaited<ReturnType<typeof usersControllerGetUser>>, TError = AxiosError<ErrorDto | ErrorDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUser>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUsersControllerGetUser<TData = Awaited<ReturnType<typeof usersControllerGetUser>>, TError = AxiosError<ErrorDto | ErrorDto>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetUser>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersControllerGetUserQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const usersControllerCreate = (
    createUserDto: CreateUserDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserDto>> => {
    
    
    return axios.post(
      `/users`,
      createUserDto,options
    );
  }



export const getUsersControllerCreateMutationOptions = <TError = AxiosError<ErrorDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerCreate>>, TError,{data: CreateUserDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerCreate>>, TError,{data: CreateUserDto}, TContext> => {

const mutationKey = ['usersControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerCreate>>, {data: CreateUserDto}> = (props) => {
          const {data} = props ?? {};

          return  usersControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerCreate>>>
    export type UsersControllerCreateMutationBody = CreateUserDto
    export type UsersControllerCreateMutationError = AxiosError<ErrorDto>

    export const useUsersControllerCreate = <TError = AxiosError<ErrorDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerCreate>>, TError,{data: CreateUserDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerCreate>>,
        TError,
        {data: CreateUserDto},
        TContext
      > => {

      const mutationOptions = getUsersControllerCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const usersControllerGetAllUsers = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserDto[]>> => {
    
    
    return axios.get(
      `/users`,options
    );
  }




export const getUsersControllerGetAllUsersQueryKey = () => {
    return [
    `/users`
    ] as const;
    }

    
export const getUsersControllerGetAllUsersQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerGetAllUsers>>, TError = AxiosError<ErrorDto>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetAllUsers>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerGetAllUsersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetAllUsers>>> = ({ signal }) => usersControllerGetAllUsers({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetAllUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerGetAllUsersQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerGetAllUsers>>>
export type UsersControllerGetAllUsersQueryError = AxiosError<ErrorDto>


export function useUsersControllerGetAllUsers<TData = Awaited<ReturnType<typeof usersControllerGetAllUsers>>, TError = AxiosError<ErrorDto>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetAllUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetAllUsers>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetAllUsers>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetAllUsers<TData = Awaited<ReturnType<typeof usersControllerGetAllUsers>>, TError = AxiosError<ErrorDto>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetAllUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetAllUsers>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetAllUsers>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerGetAllUsers<TData = Awaited<ReturnType<typeof usersControllerGetAllUsers>>, TError = AxiosError<ErrorDto>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetAllUsers>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUsersControllerGetAllUsers<TData = Awaited<ReturnType<typeof usersControllerGetAllUsers>>, TError = AxiosError<ErrorDto>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetAllUsers>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersControllerGetAllUsersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const usersControllerSetProfilePic = (
    setProfilePicDto: SetProfilePicDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserDto>> => {
    
    
    return axios.put(
      `/users/setProfilePic`,
      setProfilePicDto,options
    );
  }



export const getUsersControllerSetProfilePicMutationOptions = <TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerSetProfilePic>>, TError,{data: SetProfilePicDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerSetProfilePic>>, TError,{data: SetProfilePicDto}, TContext> => {

const mutationKey = ['usersControllerSetProfilePic'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerSetProfilePic>>, {data: SetProfilePicDto}> = (props) => {
          const {data} = props ?? {};

          return  usersControllerSetProfilePic(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerSetProfilePicMutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerSetProfilePic>>>
    export type UsersControllerSetProfilePicMutationBody = SetProfilePicDto
    export type UsersControllerSetProfilePicMutationError = AxiosError<ErrorDto | ErrorDto | ErrorDto>

    export const useUsersControllerSetProfilePic = <TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerSetProfilePic>>, TError,{data: SetProfilePicDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerSetProfilePic>>,
        TError,
        {data: SetProfilePicDto},
        TContext
      > => {

      const mutationOptions = getUsersControllerSetProfilePicMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const usersControllerSetUsername = (
    setUsernameDto: SetUsernameDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserDto>> => {
    
    
    return axios.put(
      `/users/setUsername`,
      setUsernameDto,options
    );
  }



export const getUsersControllerSetUsernameMutationOptions = <TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerSetUsername>>, TError,{data: SetUsernameDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerSetUsername>>, TError,{data: SetUsernameDto}, TContext> => {

const mutationKey = ['usersControllerSetUsername'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerSetUsername>>, {data: SetUsernameDto}> = (props) => {
          const {data} = props ?? {};

          return  usersControllerSetUsername(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerSetUsernameMutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerSetUsername>>>
    export type UsersControllerSetUsernameMutationBody = SetUsernameDto
    export type UsersControllerSetUsernameMutationError = AxiosError<ErrorDto | ErrorDto | ErrorDto>

    export const useUsersControllerSetUsername = <TError = AxiosError<ErrorDto | ErrorDto | ErrorDto>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerSetUsername>>, TError,{data: SetUsernameDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerSetUsername>>,
        TError,
        {data: SetUsernameDto},
        TContext
      > => {

      const mutationOptions = getUsersControllerSetUsernameMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    