/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */

export type AuthControllerVerifyEmail201 = {
  access_token?: string;
  refresh_token?: string;
};
