/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */
import type { MessageDto } from './messageDto';

export interface ConversationDto {
  _id: string;
  name: string;
  createdAt: string;
  groupDescription: string;
  avatar: string;
  users: string[];
  messages: MessageDto[];
}
