/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */

export type CreateListingDtoEpcRating = typeof CreateListingDtoEpcRating[keyof typeof CreateListingDtoEpcRating];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateListingDtoEpcRating = {
  A: 'A',
  B: 'B',
  C: 'C',
  D: 'D',
  E: 'E',
  F: 'F',
  G: 'G',
} as const;
