/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */

export interface CreateUserDto {
  name: string;
  email: string;
  role: string;
  imageUrl: string;
  password: string;
  emailVerificationToken: string;
  emailVerificationTokenExpires: string;
}
