/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */

export interface ErrorDto {
  /** HTTP status code */
  statusCode: number;
  /** HTTP error message */
  message: string;
  /** Error type */
  error?: string;
}
