/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */

export type ListingFurnishingStatus = typeof ListingFurnishingStatus[keyof typeof ListingFurnishingStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListingFurnishingStatus = {
  furnished: 'furnished',
  unfurnished: 'unfurnished',
  partFurnished: 'partFurnished',
} as const;
