/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */
import type { MessageDtoMessageType } from './messageDtoMessageType';

export interface MessageDto {
  _id: string;
  sender: string;
  messageType: MessageDtoMessageType;
  data: string;
  createdAt: string;
  conversation: string;
  seenUsers: string[];
  deliveredTo: string[];
}
