/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */

export type MessageDtoMessageType = typeof MessageDtoMessageType[keyof typeof MessageDtoMessageType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageDtoMessageType = {
  Text: 'Text',
  Image: 'Image',
} as const;
