/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */
import type { Step4ItemDto } from './step4ItemDto';

export interface Step4ListingDto {
  requirements: Step4ItemDto[];
}
