/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */

export interface Step3ListingDto {
  photos: string[];
  videoTourLink: string;
  floorPlanImage: string;
}
