/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */

export type UserDtoRole = typeof UserDtoRole[keyof typeof UserDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserDtoRole = {
  SUPERUSER: 'SUPERUSER',
  STUDENT: 'STUDENT',
  LANDLORD_AGENCY: 'LANDLORD_AGENCY',
} as const;
